### ISSUE TITLE
Restructure and distribute functions

### ISSUE THREAD

**Issue by maryjess** [maryjess/6nimmts#16]
Perhaps restructure functions to separate files:
```
6nimmts/
│
├── main.py
├── setup.py
├── gameplay.py
├── utils.py
└── printing.py
```

**Comment by maryjess** [comment]
Indication of code duplication:
- `simulate_debug()`
- `simulate()`

➡️ move to `simulate.py`

**Comment by Shashwat3012** [comment]
Hey @maryjess ! I would like to work on this issue. Can you please assign it to me?

**Comment by maryjess** [comment]
> Hey @maryjess ! I would like to work on this issue. Can you please assign it to me?

hi! sure, you are very welcome. 
however, please allow me to review the PR before merging to master ;)
